### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by WieturenPL** [XDgierman/school#1]
BŁĄD

Program ma za zadanie zliczać, ile jest danych cyfr w podanej liczbie. Kiedy uruchamia się program, wszystko działa, do momentu, aż program nie dotrze do pętli. Wyświetla się wówczas seria cyfr znajdujących się jedna po drugą np.

4
4
4
4
4
4
4
4
4

//To jest kod, który przedstawia mój pomysł na zliczanie konkretnych cyfr, niestety błędny.

#include <iostream>
using namespace std;

int main()
{
	int x, z, t[10], i=0, il=0;
	cout<<"podaj liczbe, z której chcesz policzyć cyfry"<<endl;
	cin>>x;
	
	cout<<"podaj cyfre, ktorej ilosc chcesz zliczyc w podanej liczbie"<<endl;
	cin>>z;
	
	
	do
	{
		t[i]=x%10;
		
		if(t[i]=z)
		{
			il++;
		}
		
		cout<<t[i]<<endl;
		i++;
	}while(x!=1);
	
	cout<<"w tej liczbie znajduje sie/znajduja sie "<<il<<" cyfry trzy"<<endl;
	
	
}

**Comment by XDgierman** [comment]
Mówiłem ci podaj plik a nie cały kod do problemu
Dobra, zerknę.

**Comment by XDgierman** [comment]
Ok, teraz widzę
Program próbuje liczyć coś z niczego
NIC nie jest wprowadzone do t[i]
Nie zapominaj wprowadzić danych z pliku!!!

**Comment by XDgierman** [comment]
Ok, to zadanie powinienem mieć jeszcze na dysku w sali

**Comment by XDgierman** [comment]
ok, sprawa rozwiązana
oto poprawiony kod

#include <iostream>
#include <fstream>
using namespace std;
int cyfry(string a, char b){
	int x=0, z=0;
	for (int j=0;j<a.length();j++){
		if (a[j]==b) z++;
		
	}
	return z;
	}

int main(){

	ifstream file;
	file.open("liczby5000.txt");
	string x;
	for (int i=0; i<5000;i++) {
	file>>x;
	if (cyfry(x,'5')>=3) {
		cout<<x<<"   "<<cyfry(x,'5')<<endl;
	};
}
}
